version: '3.8'

services:
  sensor-logger-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor-logger-server
    ports:
      - "18000:18000"
    environment:
      - SERVER_PORT=18000
      - SERVER_HOST=0.0.0.0
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DATABASE=sensor_logger
      - MONGO_TIMEOUT=10
      - MAX_DATA_STORE=1000
      - ENABLE_LOGGING=true
      - LOG_LEVEL=info
      - ENVIRONMENT=production
      - DATA_DIR=/app/data
      - ENABLE_FILE_LOG=true
    volumes:
      - sensor_data:/app/data
      - sensor_logs:/app/data/logs
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - sensor-network

  mongodb:
    image: mongo:7.0
    container_name: sensor-logger-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=sensor_logger
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: unless-stopped
    networks:
      - sensor-network

volumes:
  sensor_data:
    driver: local
  sensor_logs:
    driver: local
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  sensor-network:
    driver: bridge 