version: '3.8'

services:
  sensor-logger-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-dev}
    container_name: sensor-logger-server-dev
    ports:
      - "18000:18000"
    environment:
      - SERVER_PORT=18000
      - SERVER_HOST=0.0.0.0
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DATABASE=sensor_logger_dev
      - MONGO_TIMEOUT=10
      - MAX_DATA_STORE=1000
      - ENABLE_LOGGING=true
      - LOG_LEVEL=debug
      - ENVIRONMENT=dev
      - DATA_DIR=/app/data
      - ENABLE_FILE_LOG=true
    volumes:
      - sensor_data_dev:/app/data
      - sensor_logs_dev:/app/data/logs
      - ./:/app/src  # 挂载源代码用于开发
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - sensor-network-dev

  mongodb:
    image: mongo:7.0
    container_name: sensor-logger-mongodb-dev
    ports:
      - "27018:27017"  # 使用不同端口避免冲突
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=devpassword
      - MONGO_INITDB_DATABASE=sensor_logger_dev
    volumes:
      - mongodb_data_dev:/data/db
      - mongodb_config_dev:/data/configdb
    restart: unless-stopped
    networks:
      - sensor-network-dev

volumes:
  sensor_data_dev:
    driver: local
  sensor_logs_dev:
    driver: local
  mongodb_data_dev:
    driver: local
  mongodb_config_dev:
    driver: local

networks:
  sensor-network-dev:
    driver: bridge 